import { zValidator } from "@hono/zod-validator";
import type { Context } from "hono";
import { Hono } from "hono";
import { proxy } from "hono/proxy";
import { getConfig, type MaskingConfig } from "../config";
import { buildDebugEnvelope, isDemoEnabled } from "../debug/debugEnvelope";
import { formatMaskedRequestForLog } from "../logging/log-content";
import { logRequest } from "../logging/logger";
import type { PlaceholderContext } from "../masking/context";
import { openaiExtractor } from "../masking/extractors/openai";
import { restoreResponse } from "../masking/restorer";
import type { PIIDetectResult } from "../pii/request";
import {
  PrivacyPipelineDetectionError,
  type PrivacyPipelineResult,
  processPrivacyPipeline,
} from "../privacy/pipeline";
import { callLocal } from "../providers/local";
// Ensure all providers self-register with the registry on startup
import "../providers/gemini/provider";
import "../providers/openai/provider";
import type { ProviderResult } from "../providers/openai/client";
import { createUnmaskingStream } from "../providers/openai/stream-transformer";
import {
  DEFAULT_PROVIDER,
  type OpenAIRequest,
  OpenAIRequestSchema,
  type OpenAIResponse,
} from "../providers/openai/types";
import { providerRegistry } from "../providers/registry";
import type { SecretsProcessResult } from "../secrets/request";
import { openaiResponsesRoutes } from "./openai-responses";
import {
  createLogData,
  errorFormats,
  handleProviderError,
  setBlockedHeaders,
  setResponseHeaders,
  setStreamingHeaders,
  toPIIHeaderData,
  toPIILogData,
  toSecretsHeaderData,
  toSecretsLogData,
} from "./utils";

export const openaiRoutes = new Hono();

openaiRoutes.post(
  "/v1/chat/completions",
  zValidator("json", OpenAIRequestSchema, (result, c) => {
    if (!result.success) {
      return c.json(
        errorFormats.openai.error(
          `Invalid request body: ${result.error.message}`,
          "invalid_request_error",
        ),
        400,
      );
    }
  }),
  async (c) => {
    const startTime = Date.now();
    const request = c.req.valid("json") as OpenAIRequest;
    const config = getConfig();
    // Demo mode: opt-in via X-PromptWall-Demo header and environment check.
    const isDemoMode = isDemoEnabled(c);
    // Reuse the request ID generated by middleware (already set as response header)
    const requestId = c.req.header("x-request-id") ?? crypto.randomUUID();

    // ── Dynamic provider selection ────────────────────────────────────────────
    // Read `provider` from the request body; fall back to DEFAULT_PROVIDER ("gemini").
    // This field is stripped before the request is forwarded upstream.
    const selectedProvider: string = request.provider ?? DEFAULT_PROVIDER;

    let privacy: PrivacyPipelineResult<OpenAIRequest>;
    let afterSecretsTime = 0;
    let afterPIITime = 0;
    try {
      // Run the existing privacy pipeline. We capture timestamps around it
      // only when demo mode is active to avoid unnecessary Date.now() calls.
      privacy = await processPrivacyPipeline(request, config, openaiExtractor);
      if (isDemoMode) {
        // processPrivacyPipeline runs secrets then PII internally; we approximate
        // the split using the reported scanTimeMs from piiResult.
        afterPIITime = Date.now();
        afterSecretsTime = afterPIITime - (privacy.piiResult?.detection.scanTimeMs ?? 0);
      }
    } catch (error) {
      if (error instanceof PrivacyPipelineDetectionError) {
        console.error("PII detection error:", error.cause ?? error);
        return respondDetectionError(c, error.request as OpenAIRequest, startTime, selectedProvider);
      }
      throw error;
    }

    const { secretsResult, piiResult } = privacy;

    if (secretsResult.blocked) {
      return respondBlocked(c, request, secretsResult, startTime, selectedProvider);
    }

    if (!piiResult) {
      throw new Error("PII detection result missing from privacy pipeline");
    }

    if (config.mode === "mask") {
      return sendToProvider(c, request, {
        provider: selectedProvider,
        request: privacy.request,
        piiResult,
        piiMaskingContext: privacy.piiMaskingContext,
        secretsResult,
        startTime,
        authHeader: c.req.header("Authorization"),
        isDemoMode,
        requestId,
        afterSecretsTime,
        afterPIITime,
        privacy,
        originalRequest: request,
      });
    }

    // Route mode: send to local if PII/secrets detected, otherwise the selected provider
    const shouldRouteLocal =
      piiResult.hasPII ||
      (secretsResult.detection?.detected && config.secrets_detection.action === "route_local");

    if (shouldRouteLocal) {
      return sendToLocal(c, request, {
        request: privacy.requestAfterSecrets,
        piiResult,
        secretsResult,
        startTime,
      });
    }

    return sendToProvider(c, request, {
      provider: selectedProvider,
      request: privacy.requestAfterSecrets,
      piiResult,
      secretsResult,
      startTime,
      authHeader: c.req.header("Authorization"),
      isDemoMode,
      requestId,
      afterSecretsTime,
      afterPIITime,
      privacy,
      originalRequest: request,
    });
  },
);

openaiRoutes.route("/v1", openaiResponsesRoutes);

openaiRoutes.all("/*", (c) => {
  const normalizedPath = normalizeOpenAIPath(c.req.path);
  if (!normalizedPath || normalizedPath === "/v1/responses") {
    return c.json(
      errorFormats.openai.error(
        "Unsupported protected OpenAI endpoint",
        "invalid_request_error",
        "not_found",
      ),
      404,
    );
  }

  const config = getConfig();
  // Honour a ?provider= query param for non-chat pass-through endpoints (e.g. /models).
  const providerParam = new URL(c.req.url, "http://localhost").searchParams.get("provider");
  const catchAllProviderId = providerParam ?? "openai";
  const catchAllProvider = providerRegistry.get(catchAllProviderId);
  const fallbackUrl =
    catchAllProviderId === "openai"
      ? config.providers.openai.base_url
      : config.providers.gemini.base_url;
  const baseUrl = (catchAllProvider?.info().baseUrl as string) ?? fallbackUrl;
  const path = c.req.path.replace(/^\/openai\/v1/, "");
  const query = c.req.url.includes("?") ? c.req.url.slice(c.req.url.indexOf("?")) : "";

  return proxy(`${baseUrl}${path}${query}`, {
    ...c.req,
    headers: {
      ...c.req.header(),
      "X-Forwarded-Host": c.req.header("host"),
      host: undefined,
    },
  });
});

function normalizeOpenAIPath(path: string): string | undefined {
  let decoded = path;
  let stable = false;

  try {
    for (let pass = 0; pass < 8; pass++) {
      const next = decodeURIComponent(decoded);
      if (next === decoded) {
        stable = true;
        break;
      }
      decoded = next;
    }
  } catch {
    return undefined;
  }

  if (!stable) return undefined;

  const segments: string[] = [];
  for (const segment of decoded.replaceAll("\\", "/").split("/")) {
    const normalized = segment.split(";", 1)[0];
    if (!normalized || normalized === ".") continue;
    if (normalized === "..") {
      segments.pop();
      continue;
    }
    segments.push(normalized);
  }

  const normalized = `/${segments.join("/")}`;
  return normalized === "/openai"
    ? "/"
    : normalized.startsWith("/openai/")
      ? normalized.slice("/openai".length)
      : normalized;
}

// --- Types ---

interface ProviderOptions {
  /** The provider id to route to (e.g. "gemini", "openai"). */
  provider: string;
  request: OpenAIRequest;
  piiResult: PIIDetectResult;
  piiMaskingContext?: PlaceholderContext;
  secretsResult: SecretsProcessResult<OpenAIRequest>;
  startTime: number;
  authHeader?: string;
  /** Demo mode – set when X-PromptWall-Demo: true is present */
  isDemoMode?: boolean;
  /** Request ID from middleware, used for dashboard correlation */
  requestId?: string;
  /** Timing checkpoints captured in the main handler */
  afterSecretsTime?: number;
  afterPIITime?: number;
  /** Full pipeline result for the debug envelope builder */
  privacy?: PrivacyPipelineResult<OpenAIRequest>;
  /** The original (pre-masking) request for prompt extraction */
  originalRequest?: OpenAIRequest;
}

interface LocalOptions {
  request: OpenAIRequest;
  piiResult: PIIDetectResult;
  secretsResult: SecretsProcessResult<OpenAIRequest>;
  startTime: number;
}

// --- Helpers ---

function formatRequestForLog(request: OpenAIRequest): string | undefined {
  const config = getConfig();
  return formatMaskedRequestForLog(request, openaiExtractor, config);
}

/**
 * Strip PromptWall-internal routing fields before forwarding the request body upstream.
 * The `provider` field is consumed by our router; LLM providers do not understand it.
 */
function stripInternalFields(request: OpenAIRequest): OpenAIRequest {
  const { provider: _p, ...rest } = request as OpenAIRequest & { provider?: string };
  return rest as OpenAIRequest;
}

// --- Response handlers ---

function respondBlocked(
  c: Context,
  body: OpenAIRequest,
  secretsResult: SecretsProcessResult<OpenAIRequest>,
  startTime: number,
  provider: string,
) {
  const secretTypes = secretsResult.blockedTypes ?? [];

  setBlockedHeaders(c, secretTypes);

  logRequest(
    createLogData({
      provider,
      model: body.model || "unknown",
      startTime,
      secrets: { detected: true, types: secretTypes, masked: false },
      statusCode: 400,
      errorMessage: secretsResult.blockedReason,
    }),
    c.req.header("User-Agent") || null,
  );

  return c.json(
    errorFormats.openai.error(
      `Request blocked: detected secret material (${secretTypes.join(",")}). Remove secrets and retry.`,
      "invalid_request_error",
      "secrets_detected",
    ),
    400,
  );
}

function respondDetectionError(c: Context, body: OpenAIRequest, startTime: number, provider: string) {
  logRequest(
    createLogData({
      provider,
      model: body.model || "unknown",
      startTime,
      statusCode: 503,
      errorMessage: "Detection service unavailable",
    }),
    c.req.header("User-Agent") || null,
  );

  return c.json(
    errorFormats.openai.error(
      "Detection service unavailable",
      "server_error",
      "service_unavailable",
    ),
    503,
  );
}

// --- Provider handlers ---

/**
 * Send the (masked) request to the dynamically-selected provider.
 *
 * The provider id is read from opts.provider (set from the request body's `provider` field,
 * defaulting to DEFAULT_PROVIDER). All masking, PII pipeline, secrets handling, placeholder
 * restoration, logging, and demo-envelope logic is fully preserved.
 */
async function sendToProvider(c: Context, originalRequest: OpenAIRequest, opts: ProviderOptions) {
  const config = getConfig();
  const {
    provider: providerId,
    request,
    piiResult,
    piiMaskingContext,
    secretsResult,
    startTime,
    authHeader,
    isDemoMode = false,
    requestId = "",
    afterSecretsTime = 0,
    afterPIITime = 0,
    privacy,
    originalRequest: origReq,
  } = opts;

  const maskedContent =
    piiResult.hasPII || secretsResult.masked ? formatRequestForLog(request) : undefined;

  setResponseHeaders(
    c,
    config.mode,
    providerId,
    toPIIHeaderData(piiResult),
    toSecretsHeaderData(secretsResult),
  );

  try {
    const provider = providerRegistry.get(providerId);
    if (!provider) {
      throw new Error(
        `Provider "${providerId}" is not registered. ` +
          `Supported values: gemini, openai, anthropic, codex. ` +
          `Check that the provider is configured in config.yaml.`,
      );
    }

    // Strip our internal routing field before forwarding the request upstream
    const upstreamRequest = stripInternalFields(request);

    const result = (await provider.complete(upstreamRequest, { authHeader })) as ProviderResult;
    const afterProviderTime = isDemoMode ? Date.now() : 0;

    logRequest(
      createLogData({
        provider: providerId,
        model: result.model || originalRequest.model || "unknown",
        startTime,
        pii: toPIILogData(piiResult),
        secrets: toSecretsLogData(secretsResult),
        maskedContent,
      }),
      c.req.header("User-Agent") || null,
    );

    if (result.isStreaming) {
      // Demo mode is not supported for streaming; stream through normally.
      return respondStreaming(
        c,
        result,
        config.masking,
        piiMaskingContext,
        secretsResult.maskingContext,
      );
    }

    // Build the restored response (same as normal path)
    const restoredResponse = buildRestoredJson(
      result.response,
      config.masking,
      piiMaskingContext,
      secretsResult.maskingContext,
    );
    const afterRestoreTime = isDemoMode ? Date.now() : 0;

    // Demo mode: wrap in debug envelope and return
    if (isDemoMode && privacy) {
      const srcRequest = origReq ?? originalRequest;
      const envelope = buildDebugEnvelope({
        requestId,
        provider: providerId,
        originalMessages: srcRequest.messages as Array<{ role: string; content: unknown }>,
        maskedMessages: request.messages as Array<{ role: string; content: unknown }>,
        privacy,
        response: restoredResponse,
        startTime,
        afterSecretsTime,
        afterPIITime,
        afterProviderTime,
        afterRestoreTime,
      });
      return c.json(envelope);
    }

    return c.json(restoredResponse);
  } catch (error) {
    return handleProviderError(
      c,
      error,
      {
        provider: providerId,
        model: originalRequest.model || "unknown",
        startTime,
        pii: toPIILogData(piiResult),
        secrets: toSecretsLogData(secretsResult),
        maskedContent,
        userAgent: c.req.header("User-Agent") || null,
      },
      (msg) => errorFormats.openai.error(msg, "server_error", "upstream_error"),
    );
  }
}

async function sendToLocal(c: Context, originalRequest: OpenAIRequest, opts: LocalOptions) {
  const config = getConfig();
  const { request, piiResult, secretsResult, startTime } = opts;

  if (!config.local) {
    throw new Error("Local provider not configured");
  }

  const maskedContent =
    piiResult.hasPII || secretsResult.masked ? formatRequestForLog(request) : undefined;

  setResponseHeaders(
    c,
    config.mode,
    "local",
    toPIIHeaderData(piiResult),
    toSecretsHeaderData(secretsResult),
  );

  try {
    const result = await callLocal(stripInternalFields(request), config.local);

    logRequest(
      createLogData({
        provider: "local",
        model: result.model || originalRequest.model || "unknown",
        startTime,
        pii: toPIILogData(piiResult),
        secrets: toSecretsLogData(secretsResult),
        maskedContent,
      }),
      c.req.header("User-Agent") || null,
    );

    if (result.isStreaming) {
      setStreamingHeaders(c);
      return c.body(result.response as ReadableStream);
    }

    return c.json(result.response);
  } catch (error) {
    return handleProviderError(
      c,
      error,
      {
        provider: "local",
        model: originalRequest.model || "unknown",
        startTime,
        pii: toPIILogData(piiResult),
        secrets: toSecretsLogData(secretsResult),
        maskedContent,
        userAgent: c.req.header("User-Agent") || null,
      },
      (msg) => errorFormats.openai.error(msg, "server_error", "upstream_error"),
    );
  }
}

// --- Response formatters ---

function respondStreaming(
  c: Context,
  result: ProviderResult & { isStreaming: true },
  maskingConfig: MaskingConfig,
  piiContext?: PlaceholderContext,
  secretsContext?: PlaceholderContext,
) {
  setStreamingHeaders(c);

  if (piiContext || secretsContext) {
    const stream = createUnmaskingStream(
      result.response,
      piiContext,
      maskingConfig,
      secretsContext,
    );
    return c.body(stream);
  }

  return c.body(result.response);
}

function buildRestoredJson(
  response: OpenAIResponse,
  maskingConfig: MaskingConfig,
  piiContext?: PlaceholderContext,
  secretsContext?: PlaceholderContext,
): OpenAIResponse {
  return restoreResponse(response, openaiExtractor, maskingConfig, {
    piiContext,
    secretsContext,
  });
}
