import type { Context } from "hono";
import type { PrivacyPipelineResult } from "../privacy/pipeline";
import { DEMO_HEADER, DEMO_SECRET_HEADER, type DebugEnvelope, type DebugInfo, type DebugTimings, type PolicyDecision } from "./types";

/**
 * Checks if demo mode is active and authorized for the current request.
 * Allows localhost by default, checks for a configured secret or env variable otherwise.
 */
export function isDemoEnabled(c: Context): boolean {
  const isDemoHeader = c.req.header(DEMO_HEADER) === "true";
  if (!isDemoHeader) return false;

  // Allow localhost dev experience by default
  const host = c.req.header("host") || "";
  const isLocalhost = host.includes("localhost") || host.includes("127.0.0.1") || host.includes("[::1]");
  if (isLocalhost) return true;

  // If a demo secret is configured, require it
  const demoSecret = process.env.PROMPTWALL_DEMO_SECRET;
  if (demoSecret) {
    return c.req.header(DEMO_SECRET_HEADER) === demoSecret;
  }

  // Check explicit enable override
  const envEnabled = process.env.PROMPTWALL_DEMO_ENABLED;
  if (envEnabled !== undefined) {
    return envEnabled === "true";
  }

  // Default: disabled in production mode, enabled in dev
  return process.env.NODE_ENV !== "production";
}


// ─── Input types ─────────────────────────────────────────────────────────────

export interface BuildDebugEnvelopeInput<TRequest, TResponse> {
  /** The unique request ID (from X-Request-ID header or generated by middleware) */
  requestId: string;

  /** Provider name, e.g. "openai" or "anthropic" */
  provider: string;

  /**
   * The raw user messages before any pipeline processing.
   * We extract the last user-role content to display as the original prompt.
   */
  originalMessages: Array<{ role: string; content: unknown }>;

  /**
   * The masked messages after PII and secrets processing.
   * We extract the last user-role content to display the masked prompt.
   */
  maskedMessages: Array<{ role: string; content: unknown }>;

  /** Full privacy pipeline result – contains PII and secrets detection results */
  privacy: PrivacyPipelineResult<TRequest>;

  /**
   * The final provider response (fully restored, ready for the client).
   * Placed as `envelope.response` unchanged.
   */
  response: TResponse;

  /** Wall-clock timestamp when the request handler started */
  startTime: number;

  /**
   * Wall-clock timestamp when the pipeline finished secrets detection.
   * Pass 0 if not tracked.
   */
  afterSecretsTime: number;

  /**
   * Wall-clock timestamp when PII detection finished.
   * Pass 0 if not tracked.
   */
  afterPIITime: number;

  /**
   * Wall-clock timestamp when the provider responded.
   * Pass 0 if not tracked.
   */
  afterProviderTime: number;

  /**
   * Wall-clock timestamp when placeholder restoration finished
   * (i.e. the response is fully ready).
   * Pass 0 if not tracked.
   */
  afterRestoreTime: number;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Extracts the text content of the last user-role message from a messages array.
 * Returns an empty string if no user message is found or content is non-textual.
 */
function extractLastUserContent(messages: Array<{ role: string; content: unknown }>): string {
  for (let i = messages.length - 1; i >= 0; i--) {
    const msg = messages[i];
    if (msg.role !== "user") continue;

    if (typeof msg.content === "string") return msg.content;

    if (Array.isArray(msg.content)) {
      // OpenAI / Anthropic multimodal: extract text parts
      const parts = msg.content as Array<{ type?: string; text?: string }>;
      const textParts = parts
        .filter((p) => p.type === "text" && typeof p.text === "string")
        .map((p) => p.text as string);
      if (textParts.length > 0) return textParts.join("\n");
    }
  }
  return "";
}

/**
 * Resolves the policy decision from the pipeline result.
 * Mirrors the logic in provider route handlers.
 */
function resolvePolicyDecision(privacy: PrivacyPipelineResult<unknown>): PolicyDecision {
  if (privacy.secretsResult.blocked) return "BLOCKED";
  // If piiResult is present and hasPII with mode=route we'd return ROUTED_LOCAL,
  // but the provider routes handle that themselves. In mask mode everything that
  // reaches the provider is ALLOWED (after masking).
  return "ALLOWED";
}

/**
 * Counts total placeholder substitutions from both the PII masking context
 * and the secrets masking context.
 */
function countMasks(privacy: PrivacyPipelineResult<unknown>): number {
  const piiCount = privacy.piiMaskingContext
    ? Object.keys(privacy.piiMaskingContext.mapping).length
    : 0;
  const secretsCount = privacy.secretsResult.maskingContext
    ? Object.keys(privacy.secretsResult.maskingContext.mapping).length
    : 0;
  return piiCount + secretsCount;
}

/**
 * Collects unique PII entity type names from the detection result.
 */
function collectPIIEntities(privacy: PrivacyPipelineResult<unknown>): string[] {
  const piiResult = privacy.piiResult;
  if (!piiResult) return [];
  return [...new Set(piiResult.detection.allEntities.map((e) => e.entity_type))];
}

/**
 * Collects unique secret type names from the detection result.
 */
function collectSecretTypes(privacy: PrivacyPipelineResult<unknown>): string[] {
  const detection = privacy.secretsResult.detection;
  if (!detection?.detected) return [];
  return [...new Set(detection.matches.map((m) => m.type))];
}

/**
 * Builds the timing breakdown from the captured timestamps.
 * If a timestamp is 0 the corresponding duration is reported as 0.
 */
function buildTimings(input: {
  startTime: number;
  afterSecretsTime: number;
  afterPIITime: number;
  afterProviderTime: number;
  afterRestoreTime: number;
}): DebugTimings {
  const now = Date.now();
  const end = input.afterRestoreTime > 0 ? input.afterRestoreTime : now;

  return {
    secretsMs:
      input.afterSecretsTime > 0 ? input.afterSecretsTime - input.startTime : 0,
    piiMs:
      input.afterPIITime > 0 && input.afterSecretsTime > 0
        ? input.afterPIITime - input.afterSecretsTime
        : 0,
    providerMs:
      input.afterProviderTime > 0 && input.afterPIITime > 0
        ? input.afterProviderTime - input.afterPIITime
        : 0,
    restoreMs:
      input.afterRestoreTime > 0 && input.afterProviderTime > 0
        ? input.afterRestoreTime - input.afterProviderTime
        : 0,
    totalMs: end - input.startTime,
  };
}

// ─── Main export ─────────────────────────────────────────────────────────────

/**
 * Builds a debug envelope from already-computed pipeline state.
 *
 * All inputs are read-only references to data that the pipeline has already
 * produced. This function performs zero detection and zero masking.
 */
export function buildDebugEnvelope<TRequest, TResponse>(
  input: BuildDebugEnvelopeInput<TRequest, TResponse>,
): DebugEnvelope<TResponse> {
  const originalPrompt = extractLastUserContent(input.originalMessages);
  const maskedPrompt = extractLastUserContent(input.maskedMessages);
  const pipeline = input.privacy as PrivacyPipelineResult<unknown>;
  const piiEntities = collectPIIEntities(pipeline);
  const secretTypes = collectSecretTypes(pipeline);
  const maskCount = countMasks(pipeline);
  const policyDecision = resolvePolicyDecision(pipeline);
  const scanTimeMs = pipeline.piiResult?.detection.scanTimeMs ?? 0;
  const timings = buildTimings(input);

  // responsesRestored is true when there was something to restore
  const responsesRestored = maskCount > 0;

  const debug: DebugInfo = {
    requestId: input.requestId,
    provider: input.provider,
    originalPrompt,
    maskedPrompt,
    piiEntities,
    secretTypes,
    policyDecision,
    scanTimeMs,
    maskCount,
    responsesRestored,
    timings,
  };

  return {
    response: input.response,
    debug,
  };
}
