/**
 * @file SecurityEvent.ts
 * @module @promptwall/engine/audit
 *
 * Defines the SecurityEvent and CandidateSummary types for the M6A audit
 * logging layer.
 *
 * ── Security invariants ───────────────────────────────────────────────────────
 *
 * CandidateSummary deliberately OMITS the following Candidate fields:
 *   - value            (raw matched text — the secret / PII itself)
 *   - normalizedValue  (normalized form — still sensitive)
 *   - location         (character offsets referencing the raw content)
 *   - evidence         (detail strings may reproduce snippets of raw input)
 *   - metadata         (detector-specific; may contain raw values)
 *
 * Only classification metadata (category, subtype, severity, confidence,
 * detector name) is persisted. This guarantees that audit storage is safe
 * for broad access without exposing the sensitive content that triggered the
 * detection.
 *
 * ── No runtime dependencies ───────────────────────────────────────────────────
 *
 * This module is pure TypeScript types + a single builder function.
 * It MUST NOT import from DB, HTTP, or external service modules.
 */

import type { Candidate, CandidateCategory, Severity } from "../candidate/Candidate";
import type { PipelineResult } from "../pipeline/DetectionPipeline";

// ── CandidateSummary ─────────────────────────────────────────────────────────

/**
 * A safe, audit-loggable projection of a {@link Candidate}.
 *
 * Contains only classification metadata — never the matched text.
 *
 * @example
 * ```ts
 * // What IS stored:
 * { id: "abc", category: "secret", subtype: "AWS_ACCESS_KEY", severity: "critical",
 *   confidence: 0.99, detector: "secret-regex-detector" }
 *
 * // What is NEVER stored:
 * // value: "AKIAIOSFODNN7EXAMPLE"
 * // normalizedValue: "akiaiosfodnn7example"
 * ```
 */
export interface CandidateSummary {
  /** Candidate ID (UUID v4) — for cross-referencing with PolicyDecision.candidateIds. */
  readonly id: string;
  /** High-level detection category (e.g. "secret", "pii", "malicious"). */
  readonly category: CandidateCategory;
  /**
   * Fine-grained subtype (e.g. "AWS_ACCESS_KEY", "EMAIL_ADDRESS", "PROMPT_INJECTION").
   * Never contains the raw matched value.
   */
  readonly subtype: string;
  /** Risk severity assigned by the originating detector. */
  readonly severity: Severity;
  /**
   * Aggregated confidence score in [0.0, 1.0] as produced by ConfidenceEngine.
   * Rounded to 4 decimal places for storage compactness.
   */
  readonly confidence: number;
  /** Detector `id` string that originated this candidate (e.g. "secret-regex-detector"). */
  readonly detector: string;
}

// ── SecurityEvent ─────────────────────────────────────────────────────────────

/**
 * One audit record per {@link DetectionPipeline.run()} invocation.
 *
 * Created immediately after the pipeline produces its result — before any
 * provider call and before any HTTP response is sent.
 *
 * @example
 * ```ts
 * const event: SecurityEvent = {
 *   eventId: "550e8400-e29b-41d4-a716-446655440000",
 *   requestId: "req-abc123",
 *   timestamp: "2026-08-12T10:00:00.000Z",
 *   source: "promptwall",
 *   provider: "openai",
 *   model: "gpt-4o",
 *   candidates: [
 *     { id: "cand-1", category: "secret", subtype: "AWS_ACCESS_KEY",
 *       severity: "critical", confidence: 0.99, detector: "secret-regex-detector" }
 *   ],
 *   detectorsTriggered: ["secret-regex-detector"],
 *   riskScore: 91.4,
 *   riskLevel: "critical",
 *   action: "block",
 *   decisionReason: "Critical credential detected — request blocked.",
 *   matchedRuleIds: ["block-critical-secret"],
 *   latencyMs: 12,
 * };
 * ```
 */
export interface SecurityEvent {
  /** UUID v4 uniquely identifying this audit record. */
  readonly eventId: string;

  /**
   * Request correlation ID from the `x-request-id` header (or generated by
   * the request ID middleware). Used to cross-reference with `request_logs`.
   */
  readonly requestId: string;

  /** ISO-8601 timestamp at which the detection pipeline completed. */
  readonly timestamp: string;

  /**
   * Identifies the audit log producer.
   * Always `"promptwall"` for events generated by this gateway.
   */
  readonly source: "promptwall";

  /** LLM provider the request was targeting (e.g. `"openai"`, `"gemini"`). */
  readonly provider: string;

  /** Model name from the request body (e.g. `"gpt-4o"`). */
  readonly model: string;

  /**
   * Safe projections of every candidate produced by the pipeline.
   * Raw matched text is explicitly excluded — see {@link CandidateSummary}.
   */
  readonly candidates: readonly CandidateSummary[];

  /**
   * IDs of detectors that contributed at least one candidate.
   * Derived from {@link CandidateSummary.detector} — deduplicated.
   * Useful for per-detector effectiveness analytics.
   */
  readonly detectorsTriggered: readonly string[];

  /** Aggregated risk score in [0, 100] from {@link RiskAssessment.score}. */
  readonly riskScore: number;

  /** Categorical risk level from {@link RiskAssessment.level}. */
  readonly riskLevel: string;

  /** Policy enforcement action from {@link PolicyDecision.action}. */
  readonly action: string;

  /**
   * Human-readable reason produced by PolicyEngine.
   * MUST NOT contain raw candidate values (enforced by PolicyEngine itself).
   */
  readonly decisionReason: string;

  /**
   * IDs of all PolicyRules that matched during this evaluation.
   * @see {@link PolicyDecision.matchedRuleIds}
   */
  readonly matchedRuleIds: readonly string[];

  /**
   * Detection pipeline latency in milliseconds — time from extraction start
   * to the moment `DetectionPipeline.run()` resolved.
   * Does NOT include provider call time or privacy pipeline time.
   */
  readonly latencyMs: number;
}

// ── Builder ───────────────────────────────────────────────────────────────────

/**
 * Project a {@link PipelineResult} into a {@link SecurityEvent}.
 *
 * This is the canonical, test-friendly way to create events. Using a pure
 * function (rather than a class) keeps construction deterministic and easy
 * to unit-test without any DB or HTTP involvement.
 *
 * @param result   - The complete result from `DetectionPipeline.run()`.
 * @param opts     - Request-level context not present in `PipelineResult`.
 *
 * @example
 * ```ts
 * const event = buildSecurityEvent(pipelineResult, {
 *   requestId: "req-abc",
 *   provider: "openai",
 *   model: "gpt-4o",
 *   latencyMs: 14,
 * });
 * ```
 */
export function buildSecurityEvent(
  result: PipelineResult,
  opts: {
    readonly requestId: string;
    readonly provider: string;
    readonly model: string;
    readonly latencyMs: number;
  },
): SecurityEvent {
  const candidates: CandidateSummary[] = result.candidates.map(
    (c: Candidate): CandidateSummary => ({
      id: c.id,
      category: c.category,
      subtype: c.subtype,
      severity: c.severity,
      // Round to 4 decimal places for compact storage
      confidence: Math.round(c.confidence * 10_000) / 10_000,
      detector: c.detector,
    }),
  );

  const detectorsTriggered = [...new Set(candidates.map((c) => c.detector))];

  return {
    eventId: crypto.randomUUID(),
    requestId: opts.requestId,
    timestamp: new Date().toISOString(),
    source: "promptwall",
    provider: opts.provider,
    model: opts.model,
    candidates,
    detectorsTriggered,
    riskScore: result.riskAssessment.score,
    riskLevel: result.riskAssessment.level,
    action: result.policyDecision.action,
    decisionReason: result.policyDecision.reason,
    matchedRuleIds: [...result.policyDecision.matchedRuleIds],
    latencyMs: opts.latencyMs,
  };
}
